service: h8pdf-java

provider:
  name: aws
  runtime: java8
  memorySize: 3008
  timeout: 60

package:
  artifact: build/distributions/h8pdf.zip

functions:
  pdf-getFields:
    handler: h8pdf.GetFieldsHandler
    events:
      - http:
          path: fields
          method: post
  pdf-fillFields:
    handler: h8pdf.FillFieldsHandler
    events:
      - http:
          path: form
          method: post

